# Generated by Django 4.2.7 on 2023-11-28 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_alter_diposit_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diposit',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='interest',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
