# Generated by Django 4.2.7 on 2023-11-28 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0010_alter_diposit_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diposit',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
